# apiVersion: cloud.google.com/v1
# kind: BackendConfig
# metadata:
#   name: prometheus-backendconfig
#   namespace: iot-pipeline
# spec:
#   healthCheck:
#     checkIntervalSec: 15
#     timeoutSec: 10
#     healthyThreshold: 1
#     unhealthyThreshold: 2
#     type: HTTP
#     requestPath: /-/healthy
#     port: 9090
#   sessionAffinity:
#     affinityType: "CLIENT_IP"
#   connectionDraining:
#     drainingTimeoutSec: 60