# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: fast-ssd
#   namespace: iot-pipeline
# provisioner: kubernetes.io/gce-pd # FOr GCP, change based on cloud provider
# parameters:
#   type: pd-ssd
#   replication-type: regional-pd
# allowVolumeExpansion: true
# volumeBindingMode: WaitForFirstConsumer

# ---
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: standard-storage
#   namespace: iot-pipeline
# provisioner: kubernetes.io/gce-pd # FOr GCP, change based on cloud provider
# parameters:
#   type: pd-standard
#   replication-type: regional-pd
# allowVolumeExpansion: true
# volumeBindingMode: WaitForFirstConsumer