apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: iot-pipeline
  labels:
    app: kafka
spec:
  clusterIP: None # Headless service
  ports:
  - name: kafka
    port: 9092
    # targetPort: 9092
  - name: controller
    port: 9093
    # targetPort: 9093
  - name: jmx
    port: 7071
    # targetPort: 7071
  selector:
    app: kafka

