apiVersion: v1
kind: Service
metadata:
  name: ruuvitag-adapter
  namespace: iot-pipeline
spec:
  type: ClusterIP
  ports:
  - port: 8002
    targetPort: 8002
    name: metrics
  selector:
    app: ruuvitag-adapter

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer
  namespace: iot-pipeline
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
    name: metrics
  selector:
    app: kafka-consumer

---
apiVersion: v1
kind: Service
metadata:
  name: timescaledb-sink
  namespace: iot-pipeline
spec:
  type: ClusterIP
  ports:
  - port: 8003
    targetPort: 8003
    name: metrics
  selector:
    app: timescaledb-sink

---
