apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: grafana-backendconfig
  namespace: iot-pipeline
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 10
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /api/health
    port: 3000
  sessionAffinity:
    affinityType: "CLIENT_IP"
    affinityCookieTtlSec: 3600
  connectionDraining:
    drainingTimeoutSec: 60