---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-admin 
rules:
  - apiGroups: ['']
    resources: ['pods', 'pods/log', 'pods/exec', 'pods/attach', 'deployments', 'deployments/scale']
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-admin
roleRef:
  kind: ClusterRole
  name: pod-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: admin
    apiGroup: rbac.authorization.k8s.io
  # - kind: ServiceAccount
  #   name: pod-inspector
  #   namespace: iot-pipeline