# Kubernetes Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: iot-pipeline-sa
  namespace: iot-pipeline
  annotations:
    iam.gke.io/gcp-service-account: gke-iot-pipeline@prj-mtp-aiot-dip.iam.gserviceaccount.com
